---
- include: install_source.yml
  when: not kibana_use_repo


- include: install_debian.yml
  when: ansible_os_family == "Debian" and kibana_use_repo

- name: Configure Kibana
  template: src=kibana.yml.j2
             dest={{ kibana_dir }}/kibana/config/kibana.yml
  notify:
     - Restart Kibana

- include: plugins.yml
  tags:
   - kibana_plugins
  when: (kibana_plugins is defined)
  notify:
     - Restart Kibana


# Register Kibana service to start on boot
- name: Ensure Kibana is started on boot
  service: name=kibana enabled={{ kibana_service_startonboot }} state={{ kibana_service_state }}
