---
- include: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Configure Kibana
  template: src=kibana.yml.j2
             dest={{ kibana_dir }}/kibana/config/kibana.yml
  notify:
     - Restart Kibana
